/* Create_Group63.sql */

CREATE DATABASE IF NOT EXISTS CTSDB;

USE CTSDB;

CREATE TABLE IF NOT EXISTS VEHICLE_TYPE(
    Veh_TypeID CHAR(2),
    Veh_Type_Description VARCHAR(40), 
    PRIMARY KEY (Veh_TypeID)
) ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS VEHICLE(
    VIN CHAR(17),
    Veh_TypeID CHAR(2),
    Veh_Make VARCHAR(30),
    Veh_Model VARCHAR(30),
    Veh_Year CHAR(4),
    Veh_Colour VARCHAR(20),
    Veh_RegoNum CHAR(6),
    Veh_Odometer INT,
    Veh_Availability CHAR(1),
    Veh_For_Passenger CHAR(1),
    Veh_For_Cargo CHAR(1),
    PRIMARY KEY (VIN),
    FOREIGN KEY (Veh_TypeID) 
        REFERENCES VEHICLE_TYPE(Veh_TypeID)
) ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS PASSENGER_VEHICLE(
    VIN CHAR(1),
    Pass_seat_capacity TINYINT,
    PRIMARY KEY (VIN),
    FOREIGN KEY (VIN) 
        REFERENCES VEHICLE(VIN)
) ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS CARGO_VEHICLE(
    VIN CHAR(1),
    Carg_cfeet_capacity SMALLINT,
    Carg_tons_capacity DECIMAL(5,2),
    PRIMARY KEY (VIN),
    FOREIGN KEY (VIN) 
        REFERENCES VEHICLE(VIN)
) ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS MAINTENANCE_REPAIR(
    VIN CHAR(1),
    OdometerReading INT,
    MR_Type CHAR(1),
    MR_Date DATE,
    MR_Cost DECIMAL(7,2),
    MR_Detail VARCHAR(100),
    PRIMARY KEY (VIN, OdometerReading),
    FOREIGN KEY (VIN) 
        REFERENCES VEHICLE(VIN)
) ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS DRIVER(
    DriverLicenceNum CHAR(12),
    DriverFirstName VARCHAR(40),
    DriverLastName VARCHAR(40),
    ClearanceLevel CHAR(1),
    IsAvailable CHAR(1),
    PRIMARY KEY (DriverLicenceNum)
) ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS LANGUAGE() ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS COUNTRY() ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS OFFICIAL_ROLE() ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS OFFICIAL() ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS COUNTRY_LANGUAGE() ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS DRIVER_LANGUAGE() ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS OFFICIAL_LANGAUGE() ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS LOCATION_TYPE() ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS LOCATION() ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS TRIP() ENGINE=Innodb;
